In [4]:
import numpy as np

some_list = [4, 8, 15, 16, 23, 42]
some_tuple = (4, 8, 15, 16, 23, 42)

from_list = np.array(some_list)
from_tuple = np.array(some_tuple)

print(some_list)
print(from_list)
print(from_tuple)

print(len(from_tuple))

[4, 8, 15, 16, 23, 42]
[ 4  8 15 16 23 42]
[ 4  8 15 16 23 42]
6


In [7]:
some_list = [4, 8, 15, 16, 23, 42]
from_list = np.array(some_list)

print(from_list)
print(len(from_list))
print(from_list.shape)
print(from_list.size)
print(from_list.dtype)

[ 4  8 15 16 23 42]
6
(6,)
6
int64


In [45]:
some_list = [1, 2, 3]
some_list_with_pi = [1, 2, 3, 'pi', np.pi]

from_list = np.array(from_list)
from_list_with_pi = np.array(some_list_with_pi)

print(from_list, from_list.dtype)
print(from_list_with_pi, from_list_with_pi.dtype)
from_list_with_pi[0] = '12345678901234567890123456'
print(from_list_with_pi)

[ 4  8 15 16 23 42] int64
['1' '2' '3' 'pi' '3.141592653589793'] <U21
['123456789012345678901' '2' '3' 'pi' '3.141592653589793']


In [25]:
some_set = set('an assassins sins')
some_string = 'The quick brown fox jumps over lazy dog'

from_set = np.array(some_set)
from_string = np.array(some_string)

print(from_set, len(from_set), from_set.dtype)
print(from_string, len(from_string), from_string.dtype)

TypeError: len() of unsized object

In [27]:
some_set = set('an assassins sins')
some_string = 'The quick brown fox jumps over lazy dog'

# Если очень хочется собрать ndarray из строки или множества - оборачивает их в список
from_set = np.array(list(some_set))
from_string = np.array(list(some_string))

print(from_set, len(from_set), from_set.dtype)
print(from_string, len(from_string), from_string.dtype)

[' ' 's' 'a' 'n' 'i'] 5 <U1
['T' 'h' 'e' ' ' 'q' 'u' 'i' 'c' 'k' ' ' 'b' 'r' 'o' 'w' 'n' ' ' 'f' 'o'
 'x' ' ' 'j' 'u' 'm' 'p' 's' ' ' 'o' 'v' 'e' 'r' ' ' 'l' 'a' 'z' 'y' ' '
 'd' 'o' 'g'] 39 <U1


In [37]:
lists_in_list = [[1, 2, 3], [4, 5, 6], [1, 2, 3], [4, 5, 6]]
matrix = np.array(lists_in_list)

print(matrix)
print(matrix.shape)  # shape - вся информация о измерениях, т.е. порядок и размер
print(len(matrix)) # len - даёт информацию только о первом измерении
print(matrix.size) # size - возвращает полное количество элементов, т.е. произведение всех членов .shape

# lists_in_list[0][:-1] # две пары квадратных скобок
# matrix[0, :-1] # или две пары, или через запятую в одной паре квадртных скобок

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]
(4, 3)
4
12


array([1, 2])

In [44]:
lists_in_lists_in_list = [
                            [[11, 2, 3], [4, 5, 6], [7, 8, 9]], 
                            [[10, 11, 12], [13, 14, 15], [16, 17, 18]]
                         ]

tensor = np.array(lists_in_lists_in_list)
tensor[1, 1, 1]

14

In [57]:
bad_lists_in_list = [[1, 2, 3], [4, 5], [6, 7, 8]]
bad_array = np.array(bad_lists_in_list)

type(bad_array[0])

<ipython-input-57-55808cc84915>:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  bad_array = np.array(bad_lists_in_list)


list

In [100]:
new_array = np.ndarray(shape=(4, 4), dtype='uint8')
new_array

array([[240, 143, 139, 131],
       [ 97,  85,   0,   0],
       [  0,   0,   0,   0],
       [  1,   0,   0,   0]], dtype=uint8)

In [106]:
zeros_1d = np.zeros(10)
print(zeros_1d)
print(zeros_1d.dtype)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
float64


In [108]:
ones_2d = np.ones((10, 10))
print(ones_2d)
print(ones_2d.dtype)  # По умолчанию тип float64

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
float64


In [114]:
uint_ones = np.ones(7, 'uint8')

uint_ones[0] -= 0.2
uint_ones[1] += 0.9
uint_ones[2] += 1.1
uint_ones[3] += 300
uint_ones[4] -= 100
uint_ones[5] *= -1

uint_ones

array([  0,   1,   2,  45, 157, 255,   1], dtype=uint8)

In [121]:
np.array(range(10))
# Расширение range в np - это arange

arange10 = np.arange(10)
print(arange10, arange10.dtype)

arange2_15_5 = np.arange(2, 15, 5)
print(arange2_15_5, arange2_15_5.dtype)

float_arange = np.arange(0, 1.05, 0.1)
print(float_arange, float_arange.dtype)

[0 1 2 3 4 5 6 7 8 9] int64
[ 2  7 12] int64
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ] float64


In [126]:
# Альтернатива np.arange для равномерно расплённых массивов - это np.linspace

print(np.linspace(0, 10, 11)) # В linspace по умолчанию правая граница входит

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [129]:
default_linspace = np.linspace(0, 10)
print(default_linspace, default_linspace.shape)  # По умолчанию - разбиение отрезка идёт на 50 точек

[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ] (50,)


In [135]:
logspace = np.logspace(1, np.log10(30), 8)
print(logspace[3] / logspace[1])
print(logspace[5] / logspace[3])


1.3687381066422017
1.3687381066422017


In [140]:
np.logspace(0, 1, 3)

array([ 1.        ,  3.16227766, 10.        ])

In [166]:
np.random.rand(1, 2, 3, 4, 5, 6)

array([[[[[[0.7388439 , 0.87617644, 0.27351414, 0.32212112,
            0.22884117, 0.52634238],
           [0.71598499, 0.60546867, 0.2687838 , 0.52699958,
            0.04296817, 0.09261559],
           [0.44803749, 0.31682929, 0.34710865, 0.88563271,
            0.06011808, 0.88774517],
           [0.32842238, 0.93077882, 0.00604805, 0.82528219,
            0.45760398, 0.61151941],
           [0.21608458, 0.07981962, 0.41380402, 0.33779963,
            0.68610977, 0.31669957]],

          [[0.67285438, 0.68285427, 0.38353205, 0.75632711,
            0.33915513, 0.11080979],
           [0.21480476, 0.19297809, 0.4410863 , 0.26817929,
            0.40147612, 0.33011308],
           [0.93058635, 0.46122326, 0.76710208, 0.88291966,
            0.47154005, 0.75209822],
           [0.01385637, 0.39218784, 0.11628556, 0.7366794 ,
            0.99764635, 0.49994025],
           [0.76568983, 0.38785299, 0.29253288, 0.9331588 ,
            0.42131778, 0.94198581]],

          [[0.56576533, 0.

In [196]:
np.random.randn(10, 10)

array([[-3.26648609e-01,  1.13555634e+00,  7.89212820e-01,
         3.54527948e-01, -2.74633957e-01, -8.47249445e-02,
         1.25671864e+00,  1.57438688e+00, -6.29903965e-01,
         4.52170247e-01],
       [-4.00251730e-01,  1.83463594e+00,  1.33148476e-01,
        -2.59726789e-01, -1.94143866e-01,  6.00984689e-01,
         9.84102769e-01, -6.40025294e-01, -2.31036165e-01,
         4.44113322e-03],
       [-3.21280372e-01, -7.51153114e-01,  7.19270889e-01,
         1.40273784e+00, -1.00509122e+00,  2.75901268e-01,
         8.46839501e-01, -4.92276776e-02, -9.28369427e-03,
         1.64506544e+00],
       [ 2.36739625e-03, -7.73588925e-01, -7.49812015e-01,
        -8.86820892e-01,  1.78463448e+00,  1.16760712e+00,
         1.16885765e+00, -6.95765827e-01, -6.63920793e-01,
         2.53928156e-01],
       [ 1.16831467e+00, -1.22992545e+00,  4.16688498e-01,
        -4.80179324e-01, -8.26812644e-01,  1.81152197e+00,
        -4.51060967e-02,  1.24831420e+00, -8.30254532e-01,
         5.

In [242]:
np.random.randint(1)  # Не включительно, то есть randint(1) - возвращает только 0

lo, hi = 10, 20
np.random.randint(lo, hi, size=(10, 10))  # randint работает отлично от rand, randn, его размер передаётся через аргумент size= который может быть или таплом, или числом

array([[14, 13, 18, 10, 19, 13, 12, 19, 14, 15],
       [12, 10, 19, 15, 12, 15, 15, 10, 13, 13],
       [10, 12, 16, 15, 18, 16, 11, 16, 18, 12],
       [17, 18, 19, 10, 16, 16, 16, 12, 16, 13],
       [11, 16, 11, 19, 15, 17, 13, 12, 15, 14],
       [19, 14, 17, 14, 11, 10, 14, 11, 12, 18],
       [16, 16, 19, 14, 16, 19, 17, 11, 11, 14],
       [15, 13, 15, 19, 14, 12, 18, 15, 14, 14],
       [10, 12, 14, 13, 17, 19, 17, 16, 17, 19],
       [14, 17, 13, 10, 14, 16, 13, 11, 15, 17]])

# Векторные операции

In [254]:
list_a = [10, 20, 30]
list_b = [1, 2, 3]

arr_a = np.array(list_a)
arr_b = np.array(list_b)

print(list_a + list_b)
print(arr_a ** arr_b)  # Математические операторы с np.ndarray работают ПОЭЛЕМЕНТНО

[10, 20, 30, 1, 2, 3]
[   10   400 27000]


In [257]:
list_a = [10, 20, 30]
list_b = [2, 3, 4]

arr_a = np.array(list_a)
arr_b = np.array(list_b)

print(arr_a - arr_b)
print(arr_a + arr_b)
print(arr_a * arr_b)
print(arr_a / arr_b)
print(arr_a // arr_b)
print(arr_a % arr_b)
print(arr_a ** arr_b)

[ 8 17 26]
[12 23 34]
[ 20  60 120]
[5.         6.66666667 7.5       ]
[5 6 7]
[0 2 2]
[   100   8000 810000]


**N.B. Для матричного умножения матриц в numpy используется оператор @**

In [258]:
arr_a = np.array([2, 4, 8, 16])
b = 5

print(arr_a - b)
print(arr_a + b)
print(arr_a * b)
print(arr_a / b)
print(arr_a // b)
print(arr_a % b)
print(arr_a ** b)

[-3 -1  3 11]
[ 7  9 13 21]
[10 20 40 80]
[0.4 0.8 1.6 3.2]
[0 0 1 3]
[2 4 3 1]
[     32    1024   32768 1048576]


In [260]:
mat_a = np.array([[2, 4, 8, 16], [1, 2, 3, 4]])
b = 5

print(mat_a - b)
print(mat_a + b)
print(mat_a * b)
print(mat_a / b)
print(mat_a // b)
print(mat_a % b)
print(mat_a ** b)

[[-3 -1  3 11]
 [-4 -3 -2 -1]]
[[ 7  9 13 21]
 [ 6  7  8  9]]
[[10 20 40 80]
 [ 5 10 15 20]]
[[0.4 0.8 1.6 3.2]
 [0.2 0.4 0.6 0.8]]
[[0 0 1 3]
 [0 0 0 0]]
[[2 4 3 1]
 [1 2 3 4]]
[[     32    1024   32768 1048576]
 [      1      32     243    1024]]


## Broadcasting Rules
1. Если **размерность (количество измерений)** двух операндов различается, то форма (shape) операнда с меньшей размерностью дополняется единицами с левой стороны
1. Если **форма** двух массивов не совпадает в каком-то из измерений и у одного из операндов в этом измерении единица, то этот операнд дублируется вдоль этой оси до совпадения с большим
1. Если форма не совпадает и ни одно из измерений != 1 - то операция запрещена


In [265]:
a = np.random.randint(10, size=5)
b = np.random.randint(10, size=(1, 1, 1, 5))
c = a + b

print(a)
print(b)
print(c)
print(np.broadcast_to(a, b.shape))

[5 5 1 2 2]
[[[[1 1 9 1 6]]]]
[[[[ 6  6 10  3  8]]]]
[[[[5 5 1 2 2]]]]


In [273]:
A = np.zeros((3, 3))

b1 = np.array([1, 2, 3])
b2 = np.array([[1], [2], [3]])

print('A + b1 =\n', A + b1)
print('\nA + b2 =\n', A + b2)

A + b1 =
 [[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]

A + b2 =
 [[1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]]


# Векторные операции

Заключаются в избегании использования циклов там, где это можно

In [294]:
v1 = np.random.rand(2048 * 2)
v2 = np.random.rand(2048 * 2)

l1 = list(v1)
l2 = list(v2)

In [295]:
%%timeit
dotprod = 0
for i in range(len(l1)):
    dotprod += l1[i] * l2[i]

1.06 ms ± 18 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [296]:
%%timeit
dotprod = 0
for x, y in zip(l1, l2):
    dotprod += x * y

756 µs ± 26.3 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [297]:
%%timeit
sum(v1 * v2)

610 µs ± 24.7 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [298]:
%%timeit
np.sum(v1 * v2)

9.99 µs ± 340 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [299]:
1006 / 9.99

100.7007007007007